/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void taskHandler1(void);
void taskHandler2(void);
void taskHandler3(void);
void taskHandler4(void);


int main(void)
{
    printf("Hello Embedded World!\n");
	for(;;);
}

void taskHandler1(void)
{
	for(;;)
	{
		printf("This is task 1!\n");
	}
}
void taskHandler2(void)
{
	for(;;)
	{
		printf("This is task 2!\n");
	}
}
void taskHandler3(void)
{
	for(;;)
	{
		printf("This is task 3!\n");
	}
}
void taskHandler4(void)
{
	for(;;)
	{
		printf("This is task 4!\n");
	}
}

